### ISSUE TITLE
Error: Unexpected key 'entryPoint' found in params.overrides.containerOverrides[0]

### ISSUE THREAD

**Issue by brookemckim** [railsware/github-actions#30]
Since https://github.com/railsware/github-actions/commit/9889d87aad9ffd4c0bc373bb7c962d9ee3ea65f2 I am running into this error when using the `run-ecs-task` action.

**Comment by leonid-shevtsov** [comment]
Hey! Sorry to break this for you - we have rolled back this change in tag 1.1.3.
